engines:
  duplication:
    enabled: true
    config:
      config: .eslintrc
      languages:
        javascript:
          mass_threshold: 650
    exclude_paths:
      - 'test/'
      - 'docs/'
      - 'node_modules/'
  eslint:
    enabled: true
    channel: eslint-2
  fixme:
    enabled: true
ratings:
  paths:
    - 'bin/**.js'
    - 'src/**.js'
