--- 
$:
  preprocess:
    '$.comment.providers.github.0.token': 'eval'
    '$.comment.listen': 'eval'
  comment:
    listen: '`${ process.cwd() }/recink.comment`'       # Listen for file input (including initial content; think "tail -f")
    providers:                                          # Supported providers: github
      github:
        - token: 'process.env.GITHUB_ACCESS_TOKEN'
