--- 
$:
  preprocess:
    '$.snyk.token': 'eval'
    # '$.snyk.reporters.github.0.token': 'eval'
  snyk:
    token: 'process.env.SNYK_API_TOKEN'               # Snyk.io API token
    # actionable: true                                # Show actionable items
    # dev: false                                      # Analyze 'devDependencies'
    # reporters:                                      # Customize Reporters (available: text, github)
    #   text: ~
    #   github:
    #     - token: 'process.env.GITHUB_TOKEN'
    # fail:                                     
    #   enabled: false                                # Fail on issues found
    #   severity: 'medium'                            # Minimal severity to handle (available: low, medium, high)
