--- 
$:
  preprocess:
#   '$.comment.providers.github.0.token': 'eval'
    '$.terraform.vars.sample': 'eval'
  terraform:
#   resource-dirname: '.resource'                                           # Resource dirname relative to the module root directory (default ".resource")
#   binary: './bin/terraform'                                               # Path to Terraform binary (default "./bin/terraform")
    init: true                                                              # Initialize Terraform setup (default "true")
    plan: true                                                              # Terraform validate .tf and make a provision plan (default "true")
    apply: false                                                            # Terraform provision infrastructure (default "false")
    vars:                                                                   # Terraform variables (@see https://www.terraform.io/docs/configuration/variables.html)
      sample: 'process.env.SAMPLE_VAR'
# comment:
#   providers:                                                              # Supported providers: github
#     github:
#       - token: 'process.env.GITHUB_ACCESS_TOKEN'
